/*------------------------------------------------------------------------------------------------------------------
--	SOURCE FILE:	gps-utils.cpp -	this file will read data from the gps sensors and send it to
--					be proccessed for display to the user.	
--
--	PROGRAM:		searchGPS
--
--	FUNCTIONS:
--					void gpsLoop()
--                  void sendToPrint()
--                  void errorCheck()
--
--	DATE:			October 5, 2016
--
--	REVISIONS:		Initial version - October 5, 2016
--
--	DESIGNER:		TBD
--
--	PROGRAMMER:		TBD
--
--	NOTES:
--	This file will conatin at least two functions. One that continuously reads data from the GPS sensors,
--  and one that sends the data from those sensors to be printed on screen. It is also recommended to have
--  an error checking function in this file.
----------------------------------------------------------------------------------------------------------------------*/