/*------------------------------------------------------------------------------------------------------------------
--	SOURCE FILE:	gpsprint.cpp -	this file will print the information given by a gps tracker to
--					the user's console terminal		
--
--	PROGRAM:		printGPS
--
--	FUNCTIONS:
--					void PrintDataFunction (struct gps_data_t *gpsdata);
--
--	DATE:			October 5, 2016
--
--	REVISIONS:		Initial version - October 5, 2016
--
--	DESIGNER:		TBD
--
--	PROGRAMMER:		TBD
--
--	NOTES:
--	This file will primarily contain one function. It will take the gps_data_t structure, given to it by gps-utils.cpp,
--  and then extract the data from it and print it to the screen. It must display the following: Time Stamp (UTC),
--  Lattitude and Longitude, the PRN of each sattelite found, altitude, the azimuth, SNR, and the used flag for each
--  sattelite. A graphical implementation is not required, but will give bonus marks.
----------------------------------------------------------------------------------------------------------------------*/